// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: grpc/metric/v1/metric.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateMetricV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are assignable to RequestValue:
	//
	//	*UpdateMetricV1Request_Delta
	//	*UpdateMetricV1Request_Value
	RequestValue isUpdateMetricV1Request_RequestValue `protobuf_oneof:"request_value"`
}

func (x *UpdateMetricV1Request) Reset() {
	*x = UpdateMetricV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_metric_v1_metric_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMetricV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricV1Request) ProtoMessage() {}

func (x *UpdateMetricV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_metric_v1_metric_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricV1Request.ProtoReflect.Descriptor instead.
func (*UpdateMetricV1Request) Descriptor() ([]byte, []int) {
	return file_grpc_metric_v1_metric_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateMetricV1Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMetricV1Request) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (m *UpdateMetricV1Request) GetRequestValue() isUpdateMetricV1Request_RequestValue {
	if m != nil {
		return m.RequestValue
	}
	return nil
}

func (x *UpdateMetricV1Request) GetDelta() int64 {
	if x, ok := x.GetRequestValue().(*UpdateMetricV1Request_Delta); ok {
		return x.Delta
	}
	return 0
}

func (x *UpdateMetricV1Request) GetValue() float32 {
	if x, ok := x.GetRequestValue().(*UpdateMetricV1Request_Value); ok {
		return x.Value
	}
	return 0
}

type isUpdateMetricV1Request_RequestValue interface {
	isUpdateMetricV1Request_RequestValue()
}

type UpdateMetricV1Request_Delta struct {
	Delta int64 `protobuf:"varint,3,opt,name=delta,proto3,oneof"`
}

type UpdateMetricV1Request_Value struct {
	Value float32 `protobuf:"fixed32,4,opt,name=value,proto3,oneof"`
}

func (*UpdateMetricV1Request_Delta) isUpdateMetricV1Request_RequestValue() {}

func (*UpdateMetricV1Request_Value) isUpdateMetricV1Request_RequestValue() {}

type UpdateMetricV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  string  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Delta int64   `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Value float32 `protobuf:"fixed32,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UpdateMetricV1Response) Reset() {
	*x = UpdateMetricV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_metric_v1_metric_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMetricV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricV1Response) ProtoMessage() {}

func (x *UpdateMetricV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_metric_v1_metric_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricV1Response.ProtoReflect.Descriptor instead.
func (*UpdateMetricV1Response) Descriptor() ([]byte, []int) {
	return file_grpc_metric_v1_metric_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMetricV1Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMetricV1Response) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateMetricV1Response) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *UpdateMetricV1Response) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UpdateManyMetricV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests []*UpdateMetricV1Request `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *UpdateManyMetricV1Request) Reset() {
	*x = UpdateManyMetricV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_metric_v1_metric_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateManyMetricV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateManyMetricV1Request) ProtoMessage() {}

func (x *UpdateManyMetricV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_metric_v1_metric_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateManyMetricV1Request.ProtoReflect.Descriptor instead.
func (*UpdateManyMetricV1Request) Descriptor() ([]byte, []int) {
	return file_grpc_metric_v1_metric_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateManyMetricV1Request) GetRequests() []*UpdateMetricV1Request {
	if x != nil {
		return x.Requests
	}
	return nil
}

type UpdateManyMetricV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*UpdateMetricV1Response `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
}

func (x *UpdateManyMetricV1Response) Reset() {
	*x = UpdateManyMetricV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_metric_v1_metric_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateManyMetricV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateManyMetricV1Response) ProtoMessage() {}

func (x *UpdateManyMetricV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_metric_v1_metric_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateManyMetricV1Response.ProtoReflect.Descriptor instead.
func (*UpdateManyMetricV1Response) Descriptor() ([]byte, []int) {
	return file_grpc_metric_v1_metric_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateManyMetricV1Response) GetResponses() []*UpdateMetricV1Response {
	if x != nil {
		return x.Responses
	}
	return nil
}

type GetMetricV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *GetMetricV1Request) Reset() {
	*x = GetMetricV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_metric_v1_metric_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetricV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricV1Request) ProtoMessage() {}

func (x *GetMetricV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_metric_v1_metric_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricV1Request.ProtoReflect.Descriptor instead.
func (*GetMetricV1Request) Descriptor() ([]byte, []int) {
	return file_grpc_metric_v1_metric_proto_rawDescGZIP(), []int{4}
}

func (x *GetMetricV1Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMetricV1Request) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetMetricV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  string  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Delta int64   `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Value float32 `protobuf:"fixed32,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetMetricV1Response) Reset() {
	*x = GetMetricV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_metric_v1_metric_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetricV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricV1Response) ProtoMessage() {}

func (x *GetMetricV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_metric_v1_metric_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricV1Response.ProtoReflect.Descriptor instead.
func (*GetMetricV1Response) Descriptor() ([]byte, []int) {
	return file_grpc_metric_v1_metric_proto_rawDescGZIP(), []int{5}
}

func (x *GetMetricV1Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMetricV1Response) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetMetricV1Response) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *GetMetricV1Response) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetAllMetricV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *GetAllMetricV1Request) Reset() {
	*x = GetAllMetricV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_metric_v1_metric_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllMetricV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMetricV1Request) ProtoMessage() {}

func (x *GetAllMetricV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_metric_v1_metric_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMetricV1Request.ProtoReflect.Descriptor instead.
func (*GetAllMetricV1Request) Descriptor() ([]byte, []int) {
	return file_grpc_metric_v1_metric_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllMetricV1Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAllMetricV1Request) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetAllMetricV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*UpdateMetricV1Response `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
}

func (x *GetAllMetricV1Response) Reset() {
	*x = GetAllMetricV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_metric_v1_metric_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllMetricV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMetricV1Response) ProtoMessage() {}

func (x *GetAllMetricV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_metric_v1_metric_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMetricV1Response.ProtoReflect.Descriptor instead.
func (*GetAllMetricV1Response) Descriptor() ([]byte, []int) {
	return file_grpc_metric_v1_metric_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllMetricV1Response) GetResponses() []*UpdateMetricV1Response {
	if x != nil {
		return x.Responses
	}
	return nil
}

var File_grpc_metric_v1_metric_proto protoreflect.FileDescriptor

var file_grpc_metric_v1_metric_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2f, 0x76, 0x31,
	0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x62,
	0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01, 0x0a, 0x15, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x56, 0x31, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x07, 0xba, 0x48, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x48, 0x00, 0x52, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x68, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x5e, 0x0a, 0x19,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x79, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x08, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0x62, 0x0a, 0x1a,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x79, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x09, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x56, 0x31, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73,
	0x22, 0x38, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x56, 0x31, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x65, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x3b, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x5e,
	0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x56, 0x31,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x32, 0x98,
	0x03, 0x0a, 0x0f, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x56, 0x31, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x5f, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x56, 0x31, 0x12, 0x25, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x6b, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e,
	0x79, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x56, 0x31, 0x12, 0x29, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4d, 0x61, 0x6e, 0x79, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x56, 0x31, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x79,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x56, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x56, 0x31, 0x12,
	0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x56, 0x31,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x56, 0x31, 0x12, 0x25, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x26, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x56,
	0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x26, 0x5a, 0x24, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x56, 0x31, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2f, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_metric_v1_metric_proto_rawDescOnce sync.Once
	file_grpc_metric_v1_metric_proto_rawDescData = file_grpc_metric_v1_metric_proto_rawDesc
)

func file_grpc_metric_v1_metric_proto_rawDescGZIP() []byte {
	file_grpc_metric_v1_metric_proto_rawDescOnce.Do(func() {
		file_grpc_metric_v1_metric_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_metric_v1_metric_proto_rawDescData)
	})
	return file_grpc_metric_v1_metric_proto_rawDescData
}

var file_grpc_metric_v1_metric_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_grpc_metric_v1_metric_proto_goTypes = []any{
	(*UpdateMetricV1Request)(nil),      // 0: grpc.metric.v1.UpdateMetricV1Request
	(*UpdateMetricV1Response)(nil),     // 1: grpc.metric.v1.UpdateMetricV1Response
	(*UpdateManyMetricV1Request)(nil),  // 2: grpc.metric.v1.UpdateManyMetricV1Request
	(*UpdateManyMetricV1Response)(nil), // 3: grpc.metric.v1.UpdateManyMetricV1Response
	(*GetMetricV1Request)(nil),         // 4: grpc.metric.v1.GetMetricV1Request
	(*GetMetricV1Response)(nil),        // 5: grpc.metric.v1.GetMetricV1Response
	(*GetAllMetricV1Request)(nil),      // 6: grpc.metric.v1.GetAllMetricV1Request
	(*GetAllMetricV1Response)(nil),     // 7: grpc.metric.v1.GetAllMetricV1Response
}
var file_grpc_metric_v1_metric_proto_depIdxs = []int32{
	0, // 0: grpc.metric.v1.UpdateManyMetricV1Request.requests:type_name -> grpc.metric.v1.UpdateMetricV1Request
	1, // 1: grpc.metric.v1.UpdateManyMetricV1Response.responses:type_name -> grpc.metric.v1.UpdateMetricV1Response
	1, // 2: grpc.metric.v1.GetAllMetricV1Response.responses:type_name -> grpc.metric.v1.UpdateMetricV1Response
	0, // 3: grpc.metric.v1.MetricV1Service.UpdateMetricV1:input_type -> grpc.metric.v1.UpdateMetricV1Request
	2, // 4: grpc.metric.v1.MetricV1Service.UpdateManyMetricV1:input_type -> grpc.metric.v1.UpdateManyMetricV1Request
	4, // 5: grpc.metric.v1.MetricV1Service.GetMetricV1:input_type -> grpc.metric.v1.GetMetricV1Request
	6, // 6: grpc.metric.v1.MetricV1Service.GetAllMetricV1:input_type -> grpc.metric.v1.GetAllMetricV1Request
	1, // 7: grpc.metric.v1.MetricV1Service.UpdateMetricV1:output_type -> grpc.metric.v1.UpdateMetricV1Response
	3, // 8: grpc.metric.v1.MetricV1Service.UpdateManyMetricV1:output_type -> grpc.metric.v1.UpdateManyMetricV1Response
	5, // 9: grpc.metric.v1.MetricV1Service.GetMetricV1:output_type -> grpc.metric.v1.GetMetricV1Response
	7, // 10: grpc.metric.v1.MetricV1Service.GetAllMetricV1:output_type -> grpc.metric.v1.GetAllMetricV1Response
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grpc_metric_v1_metric_proto_init() }
func file_grpc_metric_v1_metric_proto_init() {
	if File_grpc_metric_v1_metric_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_metric_v1_metric_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMetricV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_metric_v1_metric_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMetricV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_metric_v1_metric_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateManyMetricV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_metric_v1_metric_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateManyMetricV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_metric_v1_metric_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetMetricV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_metric_v1_metric_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetMetricV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_metric_v1_metric_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllMetricV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_metric_v1_metric_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllMetricV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_grpc_metric_v1_metric_proto_msgTypes[0].OneofWrappers = []any{
		(*UpdateMetricV1Request_Delta)(nil),
		(*UpdateMetricV1Request_Value)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_metric_v1_metric_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_metric_v1_metric_proto_goTypes,
		DependencyIndexes: file_grpc_metric_v1_metric_proto_depIdxs,
		MessageInfos:      file_grpc_metric_v1_metric_proto_msgTypes,
	}.Build()
	File_grpc_metric_v1_metric_proto = out.File
	file_grpc_metric_v1_metric_proto_rawDesc = nil
	file_grpc_metric_v1_metric_proto_goTypes = nil
	file_grpc_metric_v1_metric_proto_depIdxs = nil
}
