// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: metric.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricServiceV1_UpdateMetricV1_FullMethodName     = "/grpc.metric.MetricServiceV1/UpdateMetricV1"
	MetricServiceV1_UpdateManyMetricV1_FullMethodName = "/grpc.metric.MetricServiceV1/UpdateManyMetricV1"
	MetricServiceV1_GetMetricV1_FullMethodName        = "/grpc.metric.MetricServiceV1/GetMetricV1"
	MetricServiceV1_GetAllMetricV1_FullMethodName     = "/grpc.metric.MetricServiceV1/GetAllMetricV1"
)

// MetricServiceV1Client is the client API for MetricServiceV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricServiceV1Client interface {
	UpdateMetricV1(ctx context.Context, in *MetricV1Request, opts ...grpc.CallOption) (*MetricV1Response, error)
	UpdateManyMetricV1(ctx context.Context, in *MetricV1RequestMany, opts ...grpc.CallOption) (*MetricV1ResponseMany, error)
	GetMetricV1(ctx context.Context, in *MetricV1Request, opts ...grpc.CallOption) (*MetricV1Response, error)
	GetAllMetricV1(ctx context.Context, in *MetricV1Request, opts ...grpc.CallOption) (*MetricV1ResponseMany, error)
}

type metricServiceV1Client struct {
	cc grpc.ClientConnInterface
}

func NewMetricServiceV1Client(cc grpc.ClientConnInterface) MetricServiceV1Client {
	return &metricServiceV1Client{cc}
}

func (c *metricServiceV1Client) UpdateMetricV1(ctx context.Context, in *MetricV1Request, opts ...grpc.CallOption) (*MetricV1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricV1Response)
	err := c.cc.Invoke(ctx, MetricServiceV1_UpdateMetricV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricServiceV1Client) UpdateManyMetricV1(ctx context.Context, in *MetricV1RequestMany, opts ...grpc.CallOption) (*MetricV1ResponseMany, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricV1ResponseMany)
	err := c.cc.Invoke(ctx, MetricServiceV1_UpdateManyMetricV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricServiceV1Client) GetMetricV1(ctx context.Context, in *MetricV1Request, opts ...grpc.CallOption) (*MetricV1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricV1Response)
	err := c.cc.Invoke(ctx, MetricServiceV1_GetMetricV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricServiceV1Client) GetAllMetricV1(ctx context.Context, in *MetricV1Request, opts ...grpc.CallOption) (*MetricV1ResponseMany, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricV1ResponseMany)
	err := c.cc.Invoke(ctx, MetricServiceV1_GetAllMetricV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricServiceV1Server is the server API for MetricServiceV1 service.
// All implementations must embed UnimplementedMetricServiceV1Server
// for forward compatibility.
type MetricServiceV1Server interface {
	UpdateMetricV1(context.Context, *MetricV1Request) (*MetricV1Response, error)
	UpdateManyMetricV1(context.Context, *MetricV1RequestMany) (*MetricV1ResponseMany, error)
	GetMetricV1(context.Context, *MetricV1Request) (*MetricV1Response, error)
	GetAllMetricV1(context.Context, *MetricV1Request) (*MetricV1ResponseMany, error)
	mustEmbedUnimplementedMetricServiceV1Server()
}

// UnimplementedMetricServiceV1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricServiceV1Server struct{}

func (UnimplementedMetricServiceV1Server) UpdateMetricV1(context.Context, *MetricV1Request) (*MetricV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMetricV1 not implemented")
}
func (UnimplementedMetricServiceV1Server) UpdateManyMetricV1(context.Context, *MetricV1RequestMany) (*MetricV1ResponseMany, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateManyMetricV1 not implemented")
}
func (UnimplementedMetricServiceV1Server) GetMetricV1(context.Context, *MetricV1Request) (*MetricV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetricV1 not implemented")
}
func (UnimplementedMetricServiceV1Server) GetAllMetricV1(context.Context, *MetricV1Request) (*MetricV1ResponseMany, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllMetricV1 not implemented")
}
func (UnimplementedMetricServiceV1Server) mustEmbedUnimplementedMetricServiceV1Server() {}
func (UnimplementedMetricServiceV1Server) testEmbeddedByValue()                         {}

// UnsafeMetricServiceV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricServiceV1Server will
// result in compilation errors.
type UnsafeMetricServiceV1Server interface {
	mustEmbedUnimplementedMetricServiceV1Server()
}

func RegisterMetricServiceV1Server(s grpc.ServiceRegistrar, srv MetricServiceV1Server) {
	// If the following call pancis, it indicates UnimplementedMetricServiceV1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricServiceV1_ServiceDesc, srv)
}

func _MetricServiceV1_UpdateMetricV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricServiceV1Server).UpdateMetricV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricServiceV1_UpdateMetricV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricServiceV1Server).UpdateMetricV1(ctx, req.(*MetricV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricServiceV1_UpdateManyMetricV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricV1RequestMany)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricServiceV1Server).UpdateManyMetricV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricServiceV1_UpdateManyMetricV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricServiceV1Server).UpdateManyMetricV1(ctx, req.(*MetricV1RequestMany))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricServiceV1_GetMetricV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricServiceV1Server).GetMetricV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricServiceV1_GetMetricV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricServiceV1Server).GetMetricV1(ctx, req.(*MetricV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricServiceV1_GetAllMetricV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricServiceV1Server).GetAllMetricV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricServiceV1_GetAllMetricV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricServiceV1Server).GetAllMetricV1(ctx, req.(*MetricV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricServiceV1_ServiceDesc is the grpc.ServiceDesc for MetricServiceV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricServiceV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.metric.MetricServiceV1",
	HandlerType: (*MetricServiceV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateMetricV1",
			Handler:    _MetricServiceV1_UpdateMetricV1_Handler,
		},
		{
			MethodName: "UpdateManyMetricV1",
			Handler:    _MetricServiceV1_UpdateManyMetricV1_Handler,
		},
		{
			MethodName: "GetMetricV1",
			Handler:    _MetricServiceV1_GetMetricV1_Handler,
		},
		{
			MethodName: "GetAllMetricV1",
			Handler:    _MetricServiceV1_GetAllMetricV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metric.proto",
}
